kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: node-test
  namespace: qa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
      - name: node-test
        image: 123456789.dkr.ecr.ap-south-1.amazonaws.com/node-test:COMMIT_ID
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 3
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command:
                - "sleep"
                - "60"


